/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.demo;

// import org.springframework.context.ApplicationContext;
// import org.springframework.context.support.ClassPathXmlApplicationContext;

public class App {
    // private static ApplicationContext context;

	public static String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    	/*context = new ClassPathXmlApplicationContext("Beans.xml");
        HelloWorld obj = (HelloWorld) context.getBean("helloWorld");
        obj.getMessage();*/
    	System.out.println(getGreeting());
    }
}
