/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.demo;

public class App {
	public static String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    	System.out.println(getGreeting());
    }
}
